.\" Steghide 0.5.1 man page
.TH steghide 1 "14 May 2002"
.SH NAME
steghide \- a steganography program
.SH SYNOPSIS
.B steghide
.I command
[
.I arguments
]
.SH DESCRIPTION
.B Steghide
.\" is a steganography program which embeds a secret message in a cover file by
.\" replacing some of the least significant bits of the cover file with bits of the
.\" secret message. After that, the secret message is imperceptible and can only be
.\" extracted with the correct passphrase. The result of the embedding process
.\" (an innocuous looking file with an embedded message) is called stego file.

.\" The jpeg, bmp, wav and au file formats are supported by steghide. You can use a
.\" file of any of these formats as cover/stego file. There are no restrictions on
.\" the format of the plain file.

.\" The plain data is encrypted before embedding. The encryption algorithm
.\" blowfish is used together with the hash algorithm MD5 (to create a key for
.\" blowfish from the passphrase).

.\" Together with the plain data the name of the original plain file and a crc32
.\" checksum of the plain file is embedded in the stego file. The crc32 checksum
.\" is used to verify the integrity of the embedded message during extraction.

Of course, you do not need to know graph theory to use steghide. Just keep it mind
that it boils down to finding pairs of pixels/samples that will be exchanged.

.SH COMMANDS
In this section the commands for steghide are listed. The first argument must
always be one of these commands. You can supply arguments to the embed,
extract and info commands.
#For a detailed description of these arguments see section
#.B ARGUMENTS.
.TP
.B "embed, --embed"
Embed secret data in a cover file thereby creating a stego file
.TP
.B "extract, --extract"
Extract the secret data from a stego file.
.TP
.B "info, --info"
Display information about a cover or stego file.
.TP
.B "encinfo, --encinfo"
Display a list of encryption algorithms and modes that can be used. No arguments required.
.TP
.B "version, --version"
Display a short version information. No arguments required.
.TP
.B "license, --license"
Display steghide's license. No arguments required.
.TP
.B "help, --help"
Display a help screen. No arguments required.

.SH EMBEDDING OPTIONS
.TP
.B "-ef, --embedfile \fIfilename\fP"
Specify the file that will be embedded, i.e. that contains the secret message. Note that
steghide embeds the original file name in the stego file. If you omit the -xf argument
when extracting data (see below), the embedded file will be saved to the current directory
under its original name.

.TP
.B "-cf, --coverfile \fIfilename\fP"
Specify the cover file that will be used to embed data. The cover file must be in one
of the following formats: AU, BMP, JPEG or WAV. The file-format will be detected
automatically based on header information (the extension is not relevant).

.TP
.B "-sf, --stegofile \fIfilename\fP"
Specify the name for the stego file that will be created. If this argument is omitted
when calling steghide with the embed command, then the modifications to embed the secret
data will be made to the cover file without saving it under a new name.

.TP
.B "-e, --encryption \fIalgo\fP [ \fImode\fP ] | \fImode\fP [ \fIalgo\fP ]"
Specify encryption parameters. This option must be followed by one or two strings that identify
an encryption algorithm and/or mode. You can get the names of all available algorithms and
modes with the encinfo command. The default encryption is \fBrijndael-128\fP (AES) in the \fBcbc\fP mode.
If you do not want to use encryption, use \fB-e none\fP.

.TP
.B "-z, --compress \fIlevel\fP"
Specify the compression level. The compression \fIlevel\fP can be any number in 1...9 where 1 means
best speed and 9 means best compression.

.TP
.B "-Z, --dontcompress"

.TP
.B "-a, --algorithm"

.TP
.B "-g, --goal"

.TP
.B "-r, --radius"

.TP
.B "-K, --nochecksum"
Do not embed a crc32 checksum. You can use this if the secret data already
contains some type of checksum or if you do not want to embed those extra
32 bits needed for the crc32 checksum.

.TP
.B "-N, --dontembedname"
Do not embed the file name of the secret file. If this option is used, the
extractor needs to specify a filename to tell steghide where to write the
embedded data.

.SH EXTRACTING OPTIONS
.TP
.B "-sf, --stegofile \fIfilename\fP"

.TP
.B "-xf, --extractfile \fIfilename\fP"

.\" .TP
.\" .B "-pf, --plainfile"
.\" This argument can be used with the embed and the extract command. When used
.\" with the embed command it defines the file that contains the secret message.
.\" 
.\" When this argument is used with the extract command, a file with the name passed
.\" with this command will be created and the plain data that is embedded in the
.\" stego file will be written to this file.
.\" 
.\" Note that steghide embeds the original file name of the plain file in the stego
.\" file. If you omit the -pf argument when extracting data, the embedded plain file
.\" will be saved to the current directory under its original name.
.\" 
.\" If you use the argument
.\" .B -pf -
.\" standard input or standard output will be used
.\" instead of a file. You can use this notation with the -cf and -sf arguments too.
.\" 
.\" .TP
.\" .B "-cf, --coverfile"
.\" Defines the file that is to be used as cover file, e.g.
.\" .B -cf mycover.bmp
.\" tells steghide to use the file mycover.bmp as cover file.
.\" 
.\" This argument can only be used with the embed command.

.\" .TP
.\" .B "-sf, --stegofile"
.\" Defines the file that will be used as stego file. When this argument is used
.\" with the embed command, a file of that name will be created. When used with the
.\" extract command the file must already exist and contain an embedded message.
.\" 
.\" The file format of the cover file (and the stego file) is detected automatically
.\" based on header information (the extension is not relevant). The current version
.\" of steghide supports the jpeg, bmp, wav and au file formats.

.SH COMMON OPTIONS
The following options can be used with all commands (where it makes sense).

.TP
.B "-p, --passphrase"
Use the string following this argument as the passphrase. If your
passphrase contains whitespace, you have to enclose it in quotes, e.g.
-p "a very long passphrase".

.TP
.B "-v, --verbose"
Display detailed information about the status of the embedding or extracting
process.

.TP
.B "-q, --quiet"
Supress information messages.

.TP
.B "-f, --force"
Always overwrite existing files.

.SH FILE NAME OPTIONS
.TP
All file name arguments (-cf, -ef, -sf, -xf) also accept \- as a filename which makes steghide
use standard input or standard output (whichever makes sense). Omitting the corresponding file
name argument will have the same effect with two exceptions: If -sf is omitted for the embed command,
then the modifications will be done directly in the cover file. If -xf is omitted for extraction,
the file name that is embedded in the stego file will be used. So when you want to be sure
that standard input/output is used, use - as filename.

.SH EXAMPLES

take from README !

.SH RETURN VALUE
Steghide returns 0 on success and 1 if a failure occured and it had to terminate
before completion of the requested operation. Warnings do not have an effect
on the return value.

.SH AUTHOR
Stefan Hetzl <shetzl@chello.at>
