.\" steghide 0.5.1 man page
.TH steghide 1 "14 May 2002"
.SH NAME
steghide \- a steganography program
.SH SYNOPSIS
.B steghide
.I command
[
.I arguments
]
.SH DESCRIPTION
.B Steghide
is a steganography program that is able to hide data in various kinds
of image- and audio-files. The color- respectivly sample-frequencies are not
changed thus making the embedding resistant against first-order statistical
tests.

Features include the compression of the embedded data, encryption of the embedded
data and automatic integrity checking using a checksum. The JPEG, BMP, WAV and AU
file formats are supported for use as
cover file. There are - of course - no restrictions on the format of the secret
data.

Steghide uses a graph-theoretic approach to steganography. Of course you do not need
to know anything about graph theory to use steghide and you can safely skip the rest of this section if you are 
not interested in the technical details.

The embedding algorithm roughly works as follows: At first, the secret data
is compressed and encrypted. Then a sequence of postions of pixels/samples in the cover file
is created based on a pseudo-random number generator initialized with the
passphrase (the secret data will be embedded in the pixels/samples at these positions). Of these positions
those that do not need to be changed (because they already contain the correct
value by chance) are sorted out. Then a graph-theoretic matching algorithm finds pairs of positions
such that exchanging their values has the effect of embedding the corresponding
part of the secret data. If the algorithm cannot find any more such pairs all exchanges are actually performed.
The pixels/samples at the remaining positions (the positions that are not part of such a pair) are also modified to
contain the embedded data. When you start steghide you will notice a percentage that is continually rising.
This percentage indicates the rate of positions that are members of pairs (as mentioned above). This value
can also be seen as the percentage of the secret data that can be embedded without changing the
color- respectivly sample-frequencies. Having a high percentage there means that the frequencies are
not changed much and that therefore the embedding is secure against detection by statistical tests
that analyze the color- or sample-frequencies.

The default encryption algorithm is rijndael with a key size of 128 bits (which is AES \- 
the advanced encryption standard) in the cipher block chaining mode. If you do not trust
this combination for whatever reason feel free to choose another algorithm/mode combination
(information about all possible algorithms and modes is displayed by the encinfo command).
key generation !? algorithm
The checksum is calculated using CRC32.

.SH COMMANDS
In this section the commands for steghide are listed. The first argument must
always be one of these commands. You can supply arguments to the embed,
extract and info commands.
.TP
.B "embed, --embed"
Embed secret data in a cover file thereby creating a stego file
.TP
.B "extract, --extract"
Extract the secret data from a stego file.
.TP
.B "info, --info"
Display information about a cover or stego file.
.TP
.B "encinfo, --encinfo"
Display a list of encryption algorithms and modes that can be used. No arguments required.
.TP
.B "version, --version"
Display a short version information. No arguments required.
.TP
.B "license, --license"
Display steghide's license. No arguments required.
.TP
.B "help, --help"
Display a help screen. No arguments required.

.SH EMBEDDING
You should use the \fBembed\fP command if you want to embed secret data in a cover file.

.TP
.B "-ef, --embedfile \fIfilename\fP"
Specify the file that will be embedded, i.e. that contains the secret message. Note that
steghide embeds the original file name in the stego file. If you omit the -xf argument
when extracting data (see below), the embedded file will be saved to the current directory
under its original name.

.TP
.B "-cf, --coverfile \fIfilename\fP"
Specify the cover file that will be used to embed data. The cover file must be in one
of the following formats: AU, BMP, JPEG or WAV. The file-format will be detected
automatically based on header information (the extension is not relevant).

.TP
.B "-sf, --stegofile \fIfilename\fP"
Specify the name for the stego file that will be created. If this argument is omitted
when calling steghide with the embed command, then the modifications to embed the secret
data will be made to the cover file without saving it under a new name.

.TP
.B "-e, --encryption \fIalgo\fP [ \fImode\fP ] | \fImode\fP [ \fIalgo\fP ]"
Specify encryption parameters. This option must be followed by one or two strings that identify
an encryption algorithm and/or mode. You can get the names of all available algorithms and
supported modes with the encinfo command. The default encryption is \fBrijndael-128\fP (AES) in the \fBcbc\fP mode.
If you do not want to use encryption, use \fB-e none\fP.

.TP
.B "-z, --compress \fIlevel\fP"
Specify the compression level. The compression \fIlevel\fP can be any number in 1...9 where 1 means
best speed and 9 means best compression.

.TP
.B "-Z, --dontcompress"
Do not compress the secret data before embedding it.

.TP
.B "-K, --nochecksum"
Do not embed a crc32 checksum. You can use this if the secret data already
contains some type of checksum or if you do not want to embed those extra
32 bits needed for the crc32 checksum.

.TP
.B "-N, --dontembedname"
Do not embed the file name of the secret file. If this option is used, the
extractor needs to specify a filename to tell steghide where to write the
embedded data.

.SH EXTRACTING
If you have received a file that contains a message that has been embedded
with steghide, use the \fbextract\fP command to extract it.

.TP
.B "-sf, --stegofile \fIfilename\fP"
Specify the stego file, i.e. the file that contains embedded data. If this
argument is omitted or \fIfilename\fP is \fB-\fP, steghide will read a stego
file from standard input.

.TP
.B "-xf, --extractfile \fIfilename\fP"
Create a file with the name \fIfilename\fP and write the data that is embedded
in the stego file to it. This option overrides the filename that is embedded
int the stego file. If this argument is omitted, the embedded data will be
saved to the current directory under its original name.

.SH GETTING INFORMATION ABOUT A COVER/STEGO FILE
You can use the \fbinfo\fP command to get some information about a cover or
stego file (e.g. the capacity). You might want to use this if you have received a file and you are
not sure if it contains an embedded message or if you consider using a certain
file as cover file and want to find out it's capacity.

The command line steghide info <file> will print information about <file> and
then ask you if you would like to get information about data that is embedded
in that file. If you answer with yes you have to supply the passphrase that was
used to embed the data in that file.

You can also supply the \fb"-p, --passphrase"\fP argument (see below) to the
\fbinfo\fP command which has the effect that steghide will automatically try
to get information about the data that has been embedded using the given
passphrase.

.SH COMMON OPTIONS
The following options can be used with all commands (where it makes sense).

.TP
.B "-p, --passphrase"
Use the string following this argument as the passphrase. If your
passphrase contains whitespace, you have to enclose it in quotes, e.g.
-p "a very long passphrase".

.TP
.B "-v, --verbose"
Display detailed information about the status of the embedding or extracting
process.

.TP
.B "-q, --quiet"
Supress information messages.

.TP
.B "-f, --force"
Always overwrite existing files.

.SH FILE NAME OPTIONS
.TP
All file name arguments (-cf, -ef, -sf, -xf) also accept \- as a filename which makes steghide
use standard input or standard output (whichever makes sense). Omitting the corresponding file
name argument will have the same effect with two exceptions: If -sf is omitted for the embed command,
then the modifications will be done directly in the cover file. If -xf is omitted for extraction,
then the embedded data will be saved under the file name that is embedded in the stego file.
So when you want to be sure that standard input/output is used, use - as filename.

.SH EXAMPLES

take from README !

.SH RETURN VALUE
Steghide returns 0 on success and 1 if a failure occured and it had to terminate
before completion of the requested operation. Warnings do not have an effect
on the return value.

.SH AUTHOR
Stefan Hetzl <shetzl@chello.at>
